const config = {
  api: process.env.BASE_API,
  base_dashboard: process.env.BASE_DASHBOARD,
  socket_api: process.env.SOCKET_API,
  booking_api: process.env.BASE_API,
  transactionfee: process.env.TRANSACTIONFEE,
  cognito_region: process.env.COGNITO_REGION,
  cognito_user_pool_id: process.env.COGNITO_USER_POOL_ID,
  cognito_identity_pool_id: process.env.COGNITO_IDENTITY_POOL_ID,
  cognito_app_client_id: process.env.COGNITO_APP_CLIENT_ID,
  cognito_domain: process.env.COGNITO_DOMAIN,
  cognito_scope: process.env.COGNITO_SCOPE?.split(','),
  next_auth_secret: process.env.NEXTAUTH_SECRET,
  google_maps_api_key: process.env.GOOGLE_MAPS_API_KEY,
  auth_pages: ['/paymentStays'],
  search: process.env.HOTELSEARCH_KEY,
  volindofullstory: process.env.FULL_STORY,
  airtable_base_id: process.env.AIRTABLE_BASE_ID,
  airtable_api_key: process.env.AIRTABLE_API_KEY,
  stripe_publishable_key: process.env.STRIPE_PUBLISHABLE_KEY,
  conkecta_publishable_key: process.env.CONEKTA_PUBLISHABLE_KEY,
  mercado_pago_public_key: process.env.MERCADO_PAGO_PUBLIC_KEY,
  mercado_pago_public_key_subscriptions:
    process.env.MERCADO_PAGO_PUBLIC_KEY_SUBSCRIPTIONS,
  BASICCOLOR: process.env.BASICCOLOR,
  BASICCOLORLIGHT: process.env.BASICCOLORLIGHT,
  WHITELABELEMAIL: process.env.WHITELABELEMAIL,
  WHITELABELNAME: process.env.WHITELABELNAME,
  WHITELABELNATIONALITY: process.env.WHITELABELNATIONALITY,
  WHITELABELPACKAGES: process.env.WHITELABELPACKAGES,
  SENTRY_ENVIRONMENT: process.env.SENTRY_ENVIRONMENT,
  SENTRY_AUTH_TOKEN: process.env.SENTRY_AUTH_TOKEN,
  ENVIRONMENT: process.env.ENVIRONMENT,
  GA4_TRACKING_ID: process.env.GA4_TRACKING_ID,
  DEV_CYCLE_KEY: process.env.DEV_CYCLE_KEY,
  GTM_ENVIRONMENT: process.env.GTM_ENVIRONMENT,
  SERVER_URL: process.env.SERVER_URL,
  USER_EMAIL: process.env.USER_EMAIL,
  USER_PASSWORD: process.env.USER_PASSWORD,
  HEAP_ANALYTICS: process.env.HEAP_ANALYTICS,
};
export default config;
