const iconArrayCountries = [
  { country: 'Afganistán', flag: '🇦🇫' },
  { country: 'Albania', flag: '🇦🇱' },
  { country: 'Alemania', flag: '🇩🇪' },
  { country: 'Andorra', flag: '🇦🇩' },
  { country: 'Angola', flag: '🇦🇴' },
  { country: 'Antigua y Barbuda', flag: '🇦🇬' },
  { country: 'Arabia Saudita', flag: '🇸🇦' },
  { country: 'Argentina', flag: '🇦🇷' },
  { country: 'Armenia', flag: '🇦🇲' },
  { country: 'Australia', flag: '🇦🇺' },
  { country: 'Austria', flag: '🇦🇹' },
  { country: 'Azerbaiyán', flag: '🇦🇿' },
  { country: 'Bahamas', flag: '🇧🇸' },
  { country: 'Bahréin', flag: '🇧🇭' },
  { country: 'Bangladés', flag: '🇧🇩' },
  { country: 'Barbados', flag: '🇧🇧' },
  { country: 'Bélgica', flag: '🇧🇪' },
  { country: 'Belice', flag: '🇧🇿' },
  { country: 'Benín', flag: '🇧🇯' },
  { country: 'Bielorrusia', flag: '🇧🇾' },
  { country: 'Bolivia', flag: '🇧🇴' },
  { country: 'Bosnia y Herzegovina', flag: '🇧🇦' },
  { country: 'Botsuana', flag: '🇧🇼' },
  { country: 'Brasil', flag: '🇧🇷' },
  { country: 'Brunéi', flag: '🇧🇳' },
  { country: 'Bulgaria', flag: '🇧🇬' },
  { country: 'Burkina Faso', flag: '🇧🇫' },
  { country: 'Burundi', flag: '🇧🇮' },
  { country: 'Bután', flag: '🇧🇹' },
  { country: 'Cabo Verde', flag: '🇨🇻' },
  { country: 'Camboya', flag: '🇰🇭' },
  { country: 'Camerún', flag: '🇨🇲' },
  { country: 'Canadá', flag: '🇨🇦' },
  { country: 'Catar', flag: '🇶🇦' },
  { country: 'Chad', flag: '🇹🇩' },
  { country: 'Chile', flag: '🇨🇱' },
  { country: 'China', flag: '🇨🇳' },
  { country: 'Chipre', flag: '🇨🇾' },
  { country: 'Colombia', flag: '🇨🇴' },
  { country: 'Comoras', flag: '🇰🇲' },
  { country: 'Congo', flag: '🇨🇬' },
  { country: 'Corea del Norte', flag: '🇰🇵' },
  { country: 'Corea del Sur', flag: '🇰🇷' },
  { country: 'Costa de Marfil', flag: '🇨🇮' },
  { country: 'Costa Rica', flag: '🇨🇷' },
  { country: 'Croacia', flag: '🇭🇷' },
  { country: 'Cuba', flag: '🇨🇺' },
  { country: 'Dinamarca', flag: '🇩🇰' },
  { country: 'Emiratos Árabes Unidos', flag: '🇦🇪' },
  { country: 'Estados Unidos', flag: '🇺🇸' },
  { country: 'Israel', flag: '🇮🇱' },
  { country: 'Jordania', flag: '🇯🇴' },
  { country: 'Kuwait', flag: '🇰🇼' },
  { country: 'Líbano', flag: '🇱🇧' },
  { country: 'Marruecos', flag: '🇲🇦' },
  { country: 'Palestina', flag: '🇵🇸' },
  { country: 'Qatar', flag: '🇶🇦' },
  { country: 'Siria', flag: '🇸🇾' },
  { country: 'Sudán', flag: '🇸🇩' },
  { country: 'Túnez', flag: '🇹🇳' },
  { country: 'Yemen', flag: '🇾🇪' },
  { country: 'Nueva Zelanda', flag: '🇳🇿' },
  { country: 'Mexico', flag: '🇲🇽' },
  { country: 'Mónaco', flag: '🇲🇨' },
  { country: 'Nicaragua', flag: '🇳🇮' },
  { country: 'Panamá', flag: '🇵🇦' },
  { country: 'Paraguay', flag: '🇵🇾' },
  { country: 'Rumanía', flag: '🇷🇴' },
  { country: 'Rusia', flag: '🇷🇺' },
  { country: 'Ruanda', flag: '🇷🇼' },
  { country: 'San Cristóbal y Nieves', flag: '🇰🇳' },
  { country: 'Santa Lucía', flag: '🇱🇨' },
  { country: 'San Vicente y las Granadinas', flag: '🇻🇨' },
  { country: 'Samoa', flag: '🇼🇸' },
  { country: 'San Marino', flag: '🇸🇲' },
  { country: 'Santo Tomé y Príncipe', flag: '🇸🇹' },
  { country: 'Senegal', flag: '🇸🇳' },
  { country: 'Serbia', flag: '🇷🇸' },
  { country: 'Seychelles', flag: '🇸🇨' },
  { country: 'Sierra Leona', flag: '🇸🇱' },
  { country: 'Singapur', flag: '🇸🇬' },
  { country: 'Somalia', flag: '🇸🇴' },
  { country: 'Sri Lanka', flag: '🇱🇰' },
  { country: 'Suazilandia', flag: '🇸🇿' },
  { country: 'Sudáfrica', flag: '🇿🇦' },
  { country: 'Sudán del Sur', flag: '🇸🇸' },
  { country: 'Suecia', flag: '🇸🇪' },
  { country: 'Suiza', flag: '🇨🇭' },
  { country: 'Surinam', flag: '🇸🇷' },
  { country: 'Tailandia', flag: '🇹🇭' },
  { country: 'Tanzania', flag: '🇹🇿' },
  { country: 'Tayikistán', flag: '🇹🇯' },
  { country: 'Timor Oriental', flag: '🇹🇱' },
  { country: 'Togo', flag: '🇹🇬' },
  { country: 'Tonga', flag: '🇹🇴' },
  { country: 'Trinidad y Tobago', flag: '🇹🇹' },
  { country: 'Turkmenistán', flag: '🇹🇲' },
  { country: 'Turquía', flag: '🇹🇷' },
  { country: 'Tuvalu', flag: '🇹🇻' },
  { country: 'Ucrania', flag: '🇺🇦' },
  { country: 'Uganda', flag: '🇺🇬' },
  { country: 'Uzbekistán', flag: '🇺🇿' },
  { country: 'Vanuatu', flag: '🇻🇺' },
  { country: 'Vaticano', flag: '🇻🇦' },
  { country: 'Venezuela', flag: '🇻🇪' },
  { country: 'Vietnam', flag: '🇻🇳' },
  { country: 'Yibuti', flag: '🇩🇯' },
  { country: 'Zambia', flag: '🇿🇲' },
  { country: 'Zimbabue', flag: '🇿🇼' },
  { country: 'Birmania (Myanmar)', flag: '🇲🇲' },
  { country: 'Brunei', flag: '🇧🇳' },
  { country: 'Burkina Faso', flag: '🇧🇫' },
  { country: 'Burundi', flag: '🇧🇮' },
  { country: 'Cabo Verde', flag: '🇨🇻' },
  { country: 'Camboya', flag: '🇰🇭' },
  { country: 'Camerún', flag: '🇨🇲' },
  { country: 'Canadá', flag: '🇨🇦' },
  { country: 'Catar', flag: '🇶🇦' },
  { country: 'Chad', flag: '🇹🇩' },
  { country: 'Chile', flag: '🇨🇱' },
  { country: 'China', flag: '🇨🇳' },
  { country: 'Chipre', flag: '🇨🇾' },
  { country: 'Colombia', flag: '🇨🇴' },
  { country: 'Comoras', flag: '🇰🇲' },
  { country: 'Congo', flag: '🇨🇬' },
  { country: 'Corea del Norte', flag: '🇰🇵' },
  { country: 'Corea del Sur', flag: '🇰🇷' },
  { country: 'Costa de Marfil', flag: '🇨🇮' },
  { country: 'Costa Rica', flag: '🇨🇷' },
  { country: 'Croacia', flag: '🇭🇷' },
  { country: 'Cuba', flag: '🇨🇺' },
  { country: 'Dinamarca', flag: '🇩🇰' },
  { country: 'Emiratos Árabes Unidos', flag: '🇦🇪' },
  { country: 'Eslovaquia', flag: '🇸🇰' },
  { country: 'Eslovenia', flag: '🇸🇮' },
  { country: 'España', flag: '🇪🇸' },
  { country: 'Estonia', flag: '🇪🇪' },
  { country: 'Etiopía', flag: '🇪🇹' },
  { country: 'Filipinas', flag: '🇵🇭' },
  { country: 'Finlandia', flag: '🇫🇮' },
  { country: 'Fiyi', flag: '🇫🇯' },
  { country: 'Francia', flag: '🇫🇷' },
  { country: 'Gabón', flag: '🇬🇦' },
  { country: 'Gambia', flag: '🇬🇲' },
  { country: 'Georgia', flag: '🇬🇪' },
  { country: 'Ghana', flag: '🇬🇭' },
  { country: 'Granada', flag: '🇬🇩' },
  { country: 'Grecia', flag: '🇬🇷' },
  { country: 'Guatemala', flag: '🇬🇹' },
  { country: 'Guinea', flag: '🇬🇳' },
  { country: 'Guinea-Bisáu', flag: '🇬🇼' },
  { country: 'Guinea Ecuatorial', flag: '🇬🇶' },
  { country: 'Guyana', flag: '🇬🇾' },
  { country: 'Haití', flag: '🇭🇹' },
  { country: 'Honduras', flag: '🇭🇳' },
  { country: 'Hungría', flag: '🇭🇺' },
  { country: 'India', flag: '🇮🇳' },
  { country: 'Indonesia', flag: '🇮🇩' },
  { country: 'Irán', flag: '🇮🇷' },
  { country: 'Iraq', flag: '🇮🇶' },
  { country: 'Irlanda', flag: '🇮🇪' },
  { country: 'Islandia', flag: '🇮🇸' },
  { country: 'Islas Marshall', flag: '🇲🇭' },
  { country: 'Islas Salomón', flag: '🇸🇧' },
  { country: 'Italia', flag: '🇮🇹' },
  { country: 'Jamaica', flag: '🇯🇲' },
  { country: 'Japón', flag: '🇯🇵' },
  { country: 'Kazajistán', flag: '🇰🇿' },
  { country: 'Kenia', flag: '🇰🇪' },
  { country: 'Kirguistán', flag: '🇰🇬' },
  { country: 'Kiribati', flag: '🇰🇮' },
  { country: 'Kosovo', flag: '🇽🇰' },
  { country: 'Laos', flag: '🇱🇦' },
  { country: 'Lesoto', flag: '🇱🇸' },
  { country: 'Letonia', flag: '🇱🇻' },
  { country: 'Liberia', flag: '🇱🇷' },
  { country: 'Libia', flag: '🇱🇾' },
  { country: 'Liechtenstein', flag: '🇱🇮' },
  { country: 'Lituania', flag: '🇱🇹' },
  { country: 'Luxemburgo', flag: '🇱🇺' },
  { country: 'Macedonia del Norte', flag: '🇲🇰' },
  { country: 'Madagascar', flag: '🇲🇬' },
  { country: 'Malasia', flag: '🇲🇾' },
  { country: 'Malaui', flag: '🇲🇼' },
  { country: 'Maldivas', flag: '🇲🇻' },
  { country: 'Malí', flag: '🇲🇱' },
  { country: 'Malta', flag: '🇲🇹' },
  { country: 'Marruecos', flag: '🇲🇦' },
  { country: 'Mauricio', flag: '🇲🇺' },
  { country: 'Mauritania', flag: '🇲🇷' },
  { country: 'México', flag: '🇲🇽' },
  { country: 'Micronesia', flag: '🇫🇲' },
  { country: 'Moldavia', flag: '🇲🇩' },
  { country: 'Mónaco', flag: '🇲🇨' },
  { country: 'Mongolia', flag: '🇲🇳' },
  { country: 'Montenegro', flag: '🇲🇪' },
  { country: 'Mozambique', flag: '🇲🇿' },
  { country: 'Namibia', flag: '🇳🇦' },
  { country: 'Nauru', flag: '🇳🇷' },
  { country: 'Nepal', flag: '🇳🇵' },
  { country: 'Nicaragua', flag: '🇳🇮' },
  { country: 'Níger', flag: '🇳🇪' },
  { country: 'Nigeria', flag: '🇳🇬' },
  { country: 'Noruega', flag: '🇳🇴' },
  { country: 'Omán', flag: '🇴🇲' },
  { country: 'Países Bajos', flag: '🇳🇱' },
  { country: 'Pakistán', flag: '🇵🇰' },
  { country: 'Palaos', flag: '🇵🇼' },
  { country: 'Panamá', flag: '🇵🇦' },
  { country: 'Papúa Nueva Guinea', flag: '🇵🇬' },
  { country: 'Paraguay', flag: '🇵🇾' },
  { country: 'Perú', flag: '🇵🇪' },
  { country: 'Polonia', flag: '🇵🇱' },
  { country: 'Portugal', flag: '🇵🇹' },
  { country: 'Reino Unido', flag: '🇬🇧' },
  { country: 'República Centroafricana', flag: '🇨🇫' },
  { country: 'República Checa', flag: '🇨🇿' },
  { country: 'República del Congo', flag: '🇨🇬' },
  { country: 'República Dominicana', flag: '🇩🇴' },
  { country: 'Ruanda', flag: '🇷🇼' },
  { country: 'Rumania', flag: '🇷🇴' },
  { country: 'Rusia', flag: '🇷🇺' },
  { country: 'San Cristóbal y Nieves', flag: '🇰🇳' },
  { country: 'Santa Lucía', flag: '🇱🇨' },
  { country: 'San Vicente y las Granadinas', flag: '🇻🇨' },
  { country: 'Samoa', flag: '🇼🇸' },
  { country: 'San Marino', flag: '🇸🇲' },
  { country: 'Santo Tomé y Príncipe', flag: '🇸🇹' },
  { country: 'Senegal', flag: '🇸🇳' },
  { country: 'Serbia', flag: '🇷🇸' },
  { country: 'Seychelles', flag: '🇸🇨' },
  { country: 'Sierra Leona', flag: '🇸🇱' },
  { country: 'Singapur', flag: '🇸🇬' },
  { country: 'Somalia', flag: '🇸🇴' },
  { country: 'Sri Lanka', flag: '🇱🇰' },
  { country: 'Suazilandia', flag: '🇸🇿' },
  { country: 'Sudáfrica', flag: '🇿🇦' },
  { country: 'Sudán del Sur', flag: '🇸🇸' },
  { country: 'Suecia', flag: '🇸🇪' },
  { country: 'Suiza', flag: '🇨🇭' },
  { country: 'Surinam', flag: '🇸🇷' },
  { country: 'Tailandia', flag: '🇹🇭' },
  { country: 'Tanzania', flag: '🇹🇿' },
  { country: 'Tayikistán', flag: '🇹🇯' },
  { country: 'Timor Oriental', flag: '🇹🇱' },
  { country: 'Togo', flag: '🇹🇬' },
  { country: 'Tonga', flag: '🇹🇴' },
  { country: 'Trinidad y Tobago', flag: '🇹🇹' },
  { country: 'Turkmenistán', flag: '🇹🇲' },
  { country: 'Turquía', flag: '🇹🇷' },
  { country: 'Tuvalu', flag: '🇹🇻' },
  { country: 'Ucrania', flag: '🇺🇦' },
  { country: 'Uganda', flag: '🇺🇬' },
  { country: 'Uzbekistán', flag: '🇺🇿' },
  { country: 'Vanuatu', flag: '🇻🇺' },
  { country: 'Vaticano', flag: '🇻🇦' },
  { country: 'Venezuela', flag: '🇻🇪' },
  { country: 'Vietnam', flag: '🇻🇳' },
  { country: 'Yibuti', flag: '🇩🇯' },
  { country: 'Zambia', flag: '🇿🇲' },
  { country: 'Zimbabue', flag: '🇿🇼' },
];

export const findFlagByCountry = (country: string) => {
  const countryObj = iconArrayCountries.find(obj => obj.country === country);
  if (countryObj) {
    return `${countryObj.flag} `;
  }
  return country;
};
