import { parsePhoneNumberFromString } from 'libphonenumber-js';

export function getFlightsAgentIdFromURL(id: any, isDuffel: boolean = false) {
  if (id && typeof id === 'string') {
    const identificator = isDuffel ? id.replace('D--', '') : id;
    return identificator.split('--')[1];
  } else return '';
}

export const obtainServiceTranslation = (service = '') => {
  let serviceLow = service.toLocaleLowerCase().replace(/ /g, '-');

  const servicesObj: any = {
    pool: 'Picina',
    fitness: 'Ejercicio',
    '24-hour-check-in': 'Registro las 24 horas ',
    'business-services': 'Servicios de negocios',
    'car-parking': 'Estacionamiento',
    'dry-cleaning': 'Limpieza en seco',
    'accessible-hotel': 'Hotel Accesible',
    'close-to-beach': 'Cerca de playa',
    'conference-rooms': 'Salas de conferencia',
    'balcony-/-terrace-/-patio': 'Balcon / Terraza / Patio',
    'barber-shop': 'Barberia',
    atm: 'Cajeros',
    'smoking-areas': 'Areas para fumar',
    'tennis-courts': 'Cancha de tenis',
    'airport-shuttle': 'Transporte al aeropuerto',
    bar: 'Barra',
    spa: 'Spa',
    'beach-services': 'Servicios de playa',
    'meeting-room': 'Sala de juntas',
    wifi: 'Wifi',
    babysitting: 'Cuidado de niños',
    'children-frendly': 'Amigable para los niños',
    '': 'Recepción segura',
    breakfast: 'Desayunos',
    'accessible-rooms': 'Habitaciones accesibles',
    'laundry-service': 'Servicio de lavandería',
    'coffee-in-room': 'Cafe en cuarto',
    'free-breakfast': 'Desayuno gratis',
    'genaral-shuttle-service': 'Servicio de transporte general',
    'coffee-shop-on-site': 'Cafe en el sitio',
    'non-smoking': 'Fumar no permitido',
    television: 'Televisión',
    'desk-chair': 'Silla y escritorio',
    'premium-bedding': 'Sabanas de cama premium',
    'satellite-tv-service': 'Servicio de televisión satélite',
    'refrigerator-(surcharge)': 'Refrigerador (aditional)',
    'pillowtop-mattress': 'colchón con cubierta tipo almohada',
    'laptop-friendly-workspace': 'Area de trabajo de escritorio',
    'pet-friendly-room': 'cuarto amigable para mascotas',
    'free-weekday-newspaper': 'Periodico de la semana gratis',
    'in-room-climate-control-(air-conditioning)': 'Aire acondiconado',
    'blackout-drapes/curtains': 'cortinas obscuras',
    minibar: 'mini bar',
    'wardrobe-or-closet': 'Ropero',
    'free-wired-internet': 'Internet por cable gratis',
    'coffee/tea-maker': 'Maquina de Café / Té',
    'daily-housekeeping': 'limpieza diaria',
    'free-wifi': 'Wifi gratuito',
    hdtv: 'HDTV',
    'hypo-allergenic-bedding-available': 'Sabanas hipoalergénica disponibles',
    phone: 'telefono',
    'in-room-safe-(laptop-compatible)':
      'Caja fuerte en la habitación (compatible con computadora portátil)',
    desk: 'Escritorio',
    'first-run-movies': 'películas de estreno',
    'no-rollaway/extra-beds': 'sin camas plegables/supletorias',
    'ipod-docking-station': 'estación de conexión para ipod',
    'towels-provided': 'Toallas proporcionadas',
    'premium-tv-channels': 'Canales de televisión premium',
    'bedsheets-provided': 'Sabanas proporcionadas',
    'mini-fridge': 'frigobar',
    'connecting/adjoining-rooms-available':
      'habitaciones comunicadas/contiguas disponibles',
    'shower-only': 'Solo ducha',
    'tv-size-measurement:-inch': 'medida del tamaño de tv : pulgadas',
    'private-bathroom': 'Cuarto privado',
    bathrobes: 'Batas',
    'free-toiletries': 'Artículos de aseo gratuitos',
    'hair-dryer': 'Secadora de cabello',
    'tv-size:-37': 'Tamanño de tv : 37',
    'iron/ironing-board': 'plancha/tabla de planchar',
    'pay-movies': 'Peliculas de pago',
    'lcd-tv': 'televisión LCD',
    'free-cribs/infant-beds': 'cunas/camas infantiles gratis',
    'room-service-(limited-hours)':
      'servicio de habitaciones (horario-limitado)',
    'check-in': 'registrarse',
    distance: 'Distancia ',
    '24-hour-service': 'Servicio de 24 horas',
    '24-hour-health-club': 'Servicio de 24 horas fitness',
    'roll-in-shower': 'Ducha accecible',
    'wedding-services': 'Servicios de bodas',
    'pool-facilities': 'instalaciones con piscina',
    elevator: 'Elevador',
    'fitness-facilities': 'Instalaciones de ejercicio',
    'well-lit-path-to-entrance': 'Bien iluminado el camino de entrada',
    'stair-free-path-to-entrance': 'Camido a la entrada sin escaleras',
    ' business-center': 'Centro de negocios',
    'porter/bellhop': 'Portero o botones',
    'express-check-out': 'Salida rápida',
    'valet-parking-(surcharge)': 'valet parking (cargo)',
    'computer-station': 'estacion de computadoras',
    'food-and-water-bowls': 'Tazones de comida y agua',
    terrace: 'Terraza',
    'distance-from-property-(km)---0.8':
      'Distancia desde la propiedad (km) - 0.8',
    'luggage-storage': 'Deposito de equipaje',
    'distance-from-property-(miles)---0.5':
      'Distancia desde la propiedad (millas) - 0.5',
    'atm/banking': 'Cajeros / Bancos',
    'mountain-biking-nearby': 'Rutas para bicicletas cercanas',
    'concierge-services': 'servicios de conserjería',
    'gift-shops-or-newsstand': 'Tiendas de regalo o quiosco',
    'conference-center': 'Centro de conferencias',
    'golf-lessons-available-nearby': 'lecciones de golf cercanas disponibles',
    'coffee/tea-in-common-areas': 'café/té en áreas comunes',
    'shopping-mall-on-site': 'centro comercial en el sitio',
    'meeting-rooms': 'Sala de juntas',
    'tours/ticket-assistance': 'tours/asistencia para boletos',
    'electric-car-charging-station': 'Estacion de carga eléctrica',
    'smoke-free-property': 'Propiedad libre de humo',
    'number-of-coffee-shops/cafes---2': 'Numero de cafés 2',
    'hiking/biking-trails-nearby':
      'Senderos para caminar/andar en bicicleta cerca',
    'kayaking-nearby': 'Kayaking cercano',
    'sailing-nearby': 'Navegacion cerca',
    'golfing-nearby': 'Golf cercano',
    'breakfast-available-(surcharge)': 'Desayunos disponibles (cargo)',
    ballroom: 'Salon de baile',
    'banquet-hall': 'Salón de banquetes',
    'reception-hall': 'Salón de recepción',
    'television-in-common-areas': 'Television en áreas comunes',
    'accessible-bathroom': 'Baño accesible',
    'multilingual-staff': 'El personal multilingüe',
    'assistive-listening-devices-available':
      'Dispositivos de ayuda escucha disponibles',
    'braille-or-raised-signage': 'braille o señalización en relieve',
    'valet-for-wheelchair-equipped-vehicle':
      'valet para vehículo equipado para sillas de ruedas',
    'business-center': 'Servicios de negocios',
    'air-conditioning': 'Aire acondicionado',
    'all-inclusive': 'Todos incluido',
    'allergy-friendly': 'Alergía amigable',
    'aqua-fit': 'Ejercicio acuático',
    basketball: 'Basketball',
    'bathtub-/-jacuzzi': 'Tina / Jacuzzi',
    'beauty-salon': 'Salon de belleza',
    'bicycle-services': 'Servicios de bicicletas',
    'bikes-available': 'Bicicletas disponibles',
    'billiards-/-pool': 'Billar',
    bungalows: 'Bungallows',
    'car-rental': 'Renta de automóviles',
    casino: 'Casino',
    club: 'Club',
    'double-room': 'Cuarto doble',
    'executive-rooms': 'Cuartos ejecutivos',
    'family-room': 'Cuarto familiares',
    'fire-place': 'Chimenea',
    fishing: 'pesca',
    floor: 'Piso',
    'game-room': 'Sala de juego',
    'grill/bbq': 'Asador BBQ',
    gym: 'Gimnasio',
    'in-room-safe': 'Caja fuerte en habitación',
    kitchen: 'Cosina',
    'market-near-by': 'Mercado cercano',
    meals: 'Comidas',
    newspaper: 'Periódico',
    'no-pets-allowed': 'Mascotas no permitidas',
    'non-smoking-rooms': 'Cuartos sin humo',
    'paddle-tennis': 'padel tenis',
    'pets-allowed-with-restrictions': 'mascotas admitidas con restricciones',
    'pets-friendly': 'Pet friendly',
    porterage: 'Porte',
    'private-pool': 'Alberca privada',
    'quadruple-rooms': 'Cuartos cuadruples',
    restaurants: 'Restaurantes',
    'room-size': 'Tamanño de habitación',
    Safari: 'Safari',
    'shared-bathroom': 'Baño compartido',
    'single-room': 'Cuarto simple',
    'ski-shuttle': 'lanzadera de esquí',
    'smoking-rooms': 'Cuartos con Humo',
    studios: 'Estudios',
    suites: 'Suite',
    'superior-room': 'Cuarto superior',
    'surfing-activities': 'Actividades de surf',
    'total-number-of-rooms': 'Numero total de habitaciones',
    'triple-rooms': 'Cuartos triples',
    tv: 'Televisión',
    'twin-room': 'Habitacion doble',
    villas: 'Villas',
    'vip-gaming-room': 'Sala de juego VIP',
    'water-activities': 'Actividades de agua',
    waterpark: 'Parqueo acuático',
    'yoga-classes': 'Clases de yoga',
    'in-room-climate-control-(heating)': 'Calentador en habitación (heating)',
    'height-adjustable-showerhead': 'Ducha regulable en altura',
    'closed-captioned-tv': 'Televisor con CC',
    'bathtub-or-shower': 'Tina o ducha',
    'wifi-(surcharge)': 'WIFI (cargo)',
    'lowered-electrical-outlets-in-bathroom':
      'enchufes electricos bajos en el baño',
    'led-light-bulbs': 'Focos LED',
    'lowered-peephole/view-port-in-door': 'mirador bajo / visor en puerta',
    'transfer-shower': 'ducha translado',
    'doorbell/telephone-notification': 'timbre/notificación teléfono',
    'lowered-locks/deadbolt': 'Chapas bajas / deadbolt',
    'visual-fire-alarm': 'Alarma de fuego visual',
    'lever-door-handles': 'manijas de puerta (palanca)',
    'in-room-massage-available': 'Massaje en habitación disponible',
    'tv-size:-32': 'Televisión - 32 pulgadas',
    'cable/satellite-tv-service': 'Cable TV / Servicio satelítal',
    'rollaway/extra-beds-(surcharge)': 'Camas extra / plegables (con cargo)',
    'cable-tv-service': 'Servicio cable TV',
    'free-bottled-water': 'Agua gratuita enbotellada',
    'shopping-on-site': 'Compras en el sitio',
    'internet-access-in-public-areas---surcharge':
      'WIfi en áreas públicas (cargo)',
    'safe-deposit-box-at-front-desk': 'Caja de depósito seguro en recepción',
    'bicycle-rentals-nearby': 'Renta de bicicletas cercanas',
    'visual-alarms-in-hallways': 'Alarmas visuales en pasillos',
    'express-check-in': 'Registro rapido',
    library: 'Biblioteca',
    'self-parking-(surcharge)': 'Estacionamiento (de pago)',
    'number-of-meeting-rooms---27': 'Numero de salas de reuniones - 27',
    'Designer toiletries': 'Artículos de tocador de diseño',
  };

  return servicesObj[serviceLow] || service;
};

export const validPhoneWithCountryCode = (
  phoneWithCountryCode: string
): boolean => {
  const phoneNumber = parsePhoneNumberFromString(phoneWithCountryCode);
  if (!phoneNumber) {
    return false;
  }

  return phoneNumber.isValid();
};
